app-home-create-package:
  path: /order
  controller: App\Controller\HomeController::order

app-employee:
  path: /employee
  controller: App\Controller\HomeController::employee_login

app-employee-home:
  path: /employee/dashboard
  controller: App\Controller\EmployeeController::home


app-employee-shift:
  path: /employee/dashboard/delivery/shift?{shift}
  controller: App\Controller\EmployeeShiftController::start

app-employee-profile:
  path: /employee/dashboard/profile
  controller: App\Controller\EmployeeProfileController::home

app-employee-deliver:
  path: /employee/dashboard/delivery
  controller: App\Controller\EmployeeDeliveryController::start

app-employee-office:
  path: /employee/dashboard/office
  controller: App\Controller\EmployeeOfficeController::show

app-employee-reports:
  path: /employee/dashboard/reports
  controller: App\Controller\EmployeeReportsController::show

app-employee-manage-office:
  path: /employee/dashboard/office/manage
  controller: App\Controller\EmployeeManageOffice::home

app-employee-office-vehicles:
  path: /employee/dashboard/office/vehicles
  controller: App\Controller\EmployeeVehiclesController::home

app-customer-home:
  path: /dashboard
  controller: App\Controller\CustomerController::home

app-customer-profile:
  path: /dashboard/profile
  controller: App\Controller\CustomerProfileController::home

app-customer-create-package:
  path: /dashboard/create
  controller: App\Controller\CustomerCreatePackageController::create

app-customer-orders:
  path: /dashboard/orders
  controller: App\Controller\CustomerOrdersController::list

app-customer-invoice:
  path: /dashboard/orders/invoice
  controller: App\Controller\CustomerInvoiceController::list

app-customer-invoice-id:
  path: /dashboard/orders/invoice/{id}
  controller: App\Controller\CustomerInvoiceController:viewWithID

app-customer-track:
  path: /dashboard/orders/track
  controller: App\Controller\CustomerTrackingController::list

app-customer-tracking-id:
  path: /dashboard/orders/track/{id}
  controller: App\Controller\CustomerTrackingController:viewWithID

  