
app-customer-home:
  path: /dashboard
  controller: App\Controller\CustomerController::home

app-employee-home:
  path: /employee/dashboard
  controller: App\Controller\EmployeeController::home
  
app-employee:
  path: /employee
  controller: App\Controller\HomeController::employee_login
